webpack-contrib/html-loader

index.js
test/loaderTest.js

A suggestion for how to leave URL hash fragments outside the require-statement instead of inside it. Fixes #15.

Prevents hash fragment in URLs from being parsed

---

index.js
package.json
test/loaderTest.js

Provides query interface to pass any minification parameters to html-minifier in a manner of css-loader.
I've missed `caseSensitive` minifier option at html-loader query.

Allow to pass minimize options via query params 

---

lib/attributesParser.js

Latest Vue.js syntax uses ":" characters in attributes, which is not supported in html-loader now. I added the support for these chars.

Added ":" to the list of allowed HTML attribute characters to support vuejs

---

README.md
index.js
package.json
test/loaderTest.js

Hey,
I'm re-writing angular 1.0 app and I'd like to include partials directly from templates, like so:
```html
<div id="gallery">${require("./partials/gallery.html")}</div>
```
instead of relying on `ng-include`:
```html
<div id="gallery" ng-include="'partials/gallery.html'"></div>
```
This commit adds in 2 lines of JS support for es6 interpolation in any place of the template.
I find it very useful, I hope you too.

Add support for es6 interpolation

---

index.js

I've reviewed a few sources and tried to put a safe set of minification defaults 
that will not break common use cases such as some javascript and CSS use cases.
I've used a subset of the "safe" options [from here](https://kangax.github.io/html-minifier/).
Options not used are:
- Remove redundant attributes (can break styles/JS)
- Remove empty attributes (can break styles/JS)
- Remove empty elements (if the empty tag is indeed unintended it should be removed from the original)
- Minify URLs (seems like it should be at the users discretion to rewrite absolute URLs)
This addresses a number of issues: #40, #38.

Safe set of minification defaults

---

README.md

JSHint will complain about "\.jpg$", because JS will see that string as .jpg$, not \.jpg$

Update README.md, additional backslash needed

---

index.js
test/loaderTest.js

This PR add's a second method for passing config parameters to loader. Specifying them in the webpack configuration. This is necessary in order to be able to pass more complex arguments to the html minifier. In my case I wanted to specify `ignoreCustomFragments`, which is an array containing regexes. This is currently not possible within a simple query string.
If this gets merged, developers will be able to specify the loader options like this:
// ...
htmlLoader: {
ignoreCustomFragments: [/\{\{.*?}}/]
}
// ...   
The property name can be configured via query, it defaults to `htmlLoader`
html?config=htmlLoaderSuperSpecialConfig

Add support for complex config options

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
LICENSE

- Add license
- Add Pull Request and Issue templates
- Add CONTRIBUTING.md
Resolves #68 #64

chore(project): Add project support docs

---

.editorconfig
.eslintrc
.gitignore
.jsbeautifyrc
.travis.yml
lib/attributesParser.js
package.json
test/loaderTest.js
test/parserTest.js

- Adds editorconfig
- Adds eslint package and config
- Adds jsBeautify and config
- Adds lint npm script
- Adds beautify-lint npm script
- Adds pretest npm script to exec linting
- Fixes existing linting errors
- Enable travis-ci node 4-6
- Add linting to CI run
- Add code coverage generation & reporting
- Fixes failing unit tests
- Updates project dependencies
Resolves #69 
Resolves #71

chore(ci): Bring validation tooling inline with Webpack

---

README.md
index.js
test/loaderTest.js

I added support for comma separated lists in attributes to be able to handle `srcset`
For example
``` html
```
is converted to
``` javascript
"<img src=\"" + require("./image.jpg") + "\" srcset=\"" + require("./image.jpg") + " 1x, " + require("./image@2x.jpg") + " 2x \">"
```
Gruß
-akesser-

Add support for srcset

---

README.md
index.js
test/loaderTest.js

@akesser reverting this, let us take this as a new feature altogether.
As @d3viant0ne pointed out, there are lot of edge cases for this to handle.

Revert "Add support for srcset"

---

README.md
index.js
test/loaderTest.js

The template language has `${list.href}` flag when i use Freemarker template and i want to the loader to only translate `${require('..')}` and require that.
* Impact:

only ${require('..')} to be translate.

---

README.md

extract-loader is not mentioned anywhere and it's extremely helpful to use html-loader in combination with file-loader. Allowing to require images, use full path and still output an _.html_ file.
https://github.com/webpack/html-loader/issues/62
A section at the end of the documentation, mentioning the extract-loader and providing an example usage

Mention extract loader

---

README.md
index.js
test/loaderTest.js

**What is the current behavior?**
currently html is exported via ```module.exports```
adds ability to export html as es6 default export (via ```exports.default```) when ```exportAsEs6Default``` config param is set

adds ability to export module as es6 deafult export

---

README.md
index.js
test/loaderTest.js

**What is the current behavior?**
currently we have 2 export formats: cjs (```module.exports =```, which is default), and "es6to5" (```exports.default =```, when ```exportAsEs6Default``` param is set)
this PR changes behavior of  ```exportAsEs6Default``` param to actually export ES6 default export: ```exports default "hello world";```, and brings in another param (```exportAsDefault```) to export in es6to5 format: ```exports.default = "hello world";```

adds "exportAsDefault"

---

README.md
index.js
test/loaderTest.js

there was an error in es6 default export format, that was exported as "export**s** default"
now it's exported right way, as "export default"

[export formats] fixes es6 default export

---

README.md

Update to docs
The current copy of the README.md occasionally uses the `-loader` suffix when showing examples of using `html-loader`, but most of the time simply uses the short form `html`. This will break as of Webpack v2.1.0-beta.26.
Webpack v2.1.0-beta.26 introduced a breaking change to require loaders to have the `-loader` suffix. 
This PR updates the README to show that pattern as an example instead of using the shorthand naming.
If this PR contains a breaking change, please describe the …

Update README to reflect Webpack 2 change to require -loader suffix

---

README.md

chore: update readme examples to webpack 2 syntax

---

.travis.yml
index.js
package.json

loader-utils throws a deprecation warning
updates from parseQuery to getOptions for loaderUtils
* Impact:
* Migration path for existing applications: None
* Github Issue(s) this is regarding: #113
Closes #113

fix(getOptions): deprecation warn in loaderUtils

---

README.md
test/loaderTest.js

- [ x] Tests for the changes have been added (for bug fixes / features)
- [x ] Docs have been added / updated (for bug fixes / features)
I found myself problems doing the config for the minimizer so I hope it's more clear
No behavior change
No behavior change
* Impact:
https://github.com/webpack-contrib/html-loader/issues/112 …

docs: improving docs for minimizing options in webpack config

---

README.md
index.js
test/loaderTest.js

Hi!
I'd like to propose a little change that would make possible to match every element that use a specific attribute, without bloating the config file... I work in a project that use `<custom-tags>` so currently each time we add a new element that want to load an image, we are forced to update the config file... this change would avoid that.
Tests are passing and it's not a breaking change, AFAIK.
Any feedback is welcomed.
Many thanks! ❤️

feat: add support for empty tags in `tag:attribute` matching

---

index.js
test/loaderTest.js

If I have a 'mailto' inside a href in an anchor tag file-loader tries to load a non existent file called "mailto:examplemail@exampledomain.com"
Ignore href in anchor tag if the string 'mailto:' is present
* Impact:

fix: ignore attribute if `mailto:` is present

---

index.js
test/loaderTest.js

Currently escaped quotes in inline scripts are unescaped when interpolation is enabled. You can find a minimal test case here: https://github.com/benurb/html-loader-escape-bug
interpolate=true behaves like disabled interpolation and quotes are still escaped.
The documentation states no difference between interpolate=true and false regarding the handling of escaped quotes.
This solution is very hacky, but I …

fix(index): escape double quotes correctly (`options.interpolate`)

---

README.md
src/index.js
src/options.json
src/plugins/import.js
test/fixtures/options/import/filter/fixture.html
test/fixtures/options/import/filter/fixture.js
test/options/__snapshots__/import.test.js.snap
test/options/import.test.js

- Fixes #158
**webpack.config.js**
```js
{
loader: 'html-loader',
options: {
import: false
}
}
```
**webpack.config.js**
```js
{
loader: 'html-loader',
options: {
import: /filter/
}
}
```
**webpack.config.js**
```js
{
loader: 'html-loader',
options: {
import (url) {
return /filter/.test(url)
}
}
}
```

[WIP] feat(import): add `<import>` filter support (`options.import`)

---

README.md
src/index.js
src/options.json
src/plugins/url.js
test/fixtures/options/url/filter/fixture.html
test/fixtures/options/url/filter/fixture.js
test/options/__snapshots__/url.test.js.snap
test/options/url.test.js

- Fixes #158
**webpack.config.js**
```js
{
loader: 'html-loader',
options: {
url: false
}
}
```
**webpack.config.js**
```js
{
loader: 'html-loader',
options: {
url: /filter/
}
}
```
**webpack.config.js**
```js
{
loader: 'html-loader',
options: {
url (url) {
return /filter/.test(url)
}
}
}
```

feat(plugins/url): add `url` filter support (`options.url`)

---

index.js

This fixes bug #150 where the URL passed to `require()` would have `./` prepended when it shouldn't.
https://github.com/webpack-contrib/html-loader/issues/150
`require`, when interpolated, will no longer prepend `./` to the request url.
* Impact:

fix(index): don't prepend `./` to the URL on `interpolate=require` (`options.interpolate`)

---

README.md

According to https://github.com/webpack/webpack/issues/3713#issuecomment-270365920 `use: [ 'file-loader?name=[path][name].[ext]!extract-loader!html-loader' ]` is not expected to work (and it didn't work for me using wepack 4 and latest version of `html-loader`).
* Impact:

docs(readme): migrate from deprecated `!` loader syntax

---

src/index.js
test/loader.test.js

fix: do not handle empty attributes

---

README.md
src/constants.js
src/index.js
src/utils.js
test/loader.test.js
test/minimize-option.test.js

Refactor `minimize` option
Yes
BREAKING CHANGE: the `minimize` option is `true` by default in `production` mode. You need to list all options for `html-minifier` if you use `object` notation.
No

refactor: the `minimize` option

---

README.md
src/index.js
src/options.json
src/utils.js
test/attributes-option.test.js
test/loader.test.js

Refactor the `attrs` option + allow to set it to `true`
Yes, the `attrs` option was renamed to the `attributes` option
No

refactor: `attrs` option

---

README.md
src/index.js
src/options.json
test/__snapshots__/interpolate-option.test.js.snap
test/__snapshots__/validate-options.test.js.snap
test/interpolate-option.test.js
test/validate-options.test.js

Drop `require`
Yes
BREAKING CHANGE: the `require` value for the `interpolation` option was removed with replacement, please use `raw-loader`, the special loader for syntax (for example - `ejs-loader`)  or template literal for that. Non standard HTML syntax potential can be broken by minimizer, parser can throw an error in some cases.
No

refactor: remove the `require` value for the `interpolate` option

---

src/utils.js
test/__snapshots__/loader.test.js.snap
test/fixtures/invisible-space.html
test/loader.test.js

fix: escape `\u2028` and `\u2029` characters

---

README.md
src/plugins/source-plugin.js

- [] **test update** 
handle only valid srcset tags
No
No

fix: handle only valid srcset tags

---

README.md
src/index.js
test/__snapshots__/preprocessor-option.test.js.snap
test/preprocessor-option.test.js

feat: add support for async functions to preprocessor option

---

src/index.js
src/plugins/minimizer-plugin.js
src/plugins/source-plugin.js
src/utils.js

refactor: code

---

src/options.json
src/plugins/source-plugin.js
test/__snapshots__/attributes-option.test.js.snap
test/__snapshots__/validate-options.test.js.snap
test/attributes-option.test.js

it is not ready for release, but we need release ASAP
No
Will be implemented in future

refactor: postpone `include` feature

---

README.md
src/options.json
src/utils.js
test/__snapshots__/attributes-option.test.js.snap
test/attributes-option.test.js
test/validate-options.test.js

feat: `...` syntax to extend default tag and attributes

---

src/utils.js
test/__snapshots__/loader.test.js.snap
test/fixtures/other-loader-query.html
test/fixtures/other-loader-query.js
test/helpers/svg-color-loader.js
test/loader.test.js

Pass query with hash to other loaders
No
No

fix: pass query with hash to other loaders

---

README.md
src/plugins/sources-plugin.js
src/utils.js
test/__snapshots__/loader.test.js.snap
test/fixtures/webpackIgnore.html
test/fixtures/webpackIgnore.js
test/loader.test.js

added support `` comment
No
No

Feat: added support webpackIgnore comment

---

test/__snapshots__/sources-option.test.js.snap
test/fixtures/resolve-roots.html
test/fixtures/resolve-roots.js
test/sources-option.test.js

fixes #381
No
add test on `resolve.roots`

test: resolve.roots

---

src/utils.js

fix: context for loader without resource

---

.github/workflows/nodejs.yml

use latest node version 16.
No
No

chore: use node v16 for lint job

---

src/utils.js

Some performance improvement and refactoring

---

README.md

fixes https://github.com/webpack-contrib/html-loader/issues/404
No
No

docs: remove `extract-loader`

---

README.md
src/index.js
src/utils.js
test/__snapshots__/esModule-option.test.js.snap
test/__snapshots__/loader.test.js.snap
test/__snapshots__/minimize-option.test.js.snap
test/__snapshots__/postprocessor-option.test.js.snap
test/__snapshots__/preprocessor-option.test.js.snap
test/__snapshots__/sources-option.test.js.snap
test/postprocessor-option.test.js

feat: using template literals in code when it supported
