webpack-contrib/html-loader

lib/attributesParser.js
test/parserTest.js

Support single quotes for attributes as well as double quotes. fixes #18

---

README.md

Add attrs=false to README.md

---

.gitignore
lib/attributesParser.js
test/loaderTest.js
test/parserTest.js

* adds support for alphanumeric attributes
* updates parser test case
* fixes loader test case

Alphanumeric attributes

---

lib/attributesParser.js
test/parserTest.js

The support was removed during 96be647170014edac168bb3ff118cfd212b3d944. I fixed the regex again and added a unit test to make sure it will not get lost again ;)

Attribute colon support added including tests

---

README.md

Hi,
At first I was stuck trying to make the loader work with images and favicons hosted in a different folder... but once I figured out how to do so, I thought that it would be useful for other users with the same issue to update the readme so I ended up doing so.
I don't know if this is the proper way to do it, any comment or suggestion is welcome. :smile:
Thanks!

Update README.md, advanced options section

---

README.md

**What kind of change does this PR introduce?**

docs(README): change style, add logos, badges, maintainers && LICENSE

---

README.md

Targets coveralls, Tobias instructed us to use codecov.io
Adds the Codecov badge for branch=master
* Impact:

chore(docs): Update Coverage Badge URL

---

package.json

Throws a license warning on install as it uses the old `licenses` key
Removes the license warning on install
* Impact: N/A
* Migration path for existing applications: N/A
* Github Issue(s) this is regarding: N/A

chore(proj): Update to new license syntax

---

README.md

Incorrect reference of compiled extension in the example:
```js
require("html!./file.html");
// => '<img src="http://cdn.example.com/49eba9f/a992ca.jpg"
//         data-src="image2x.png">'
```
Corrected the extension to `png`/
Discussion about this can be seen at #82.

Made the examples consistent

---

README.md

Minor correction to README config format

---

LICENSE
README.md

**Relicense for JSF Compability**
:shipit:  @hemanth @TheLarkInn @SpaceK33z :)

docs(LICENSE): relicense to JSF

---

README.md

docs(README): add link to `html-minifier` options (`options.minimize`)

---

src/utils.js

Use `startsWith()` which results in much concise code.
N/A
N/A

chore(utils): Minor code refactoring

---

README.md
src/options.json

Refactor README + fix schema options
Yes, but we don't do release so no problems 
No

docs: refactor

---

test/attributes-option.test.js
test/esModule-option.test.js
test/interpolate-option.test.js
test/loader.test.js
test/root-options.test.js

test: refactor

---

package-lock.json
package.json
src/index.js
test/minimize-option.test.js

fix: support ES6 syntax in `script` tags when minimize

---

src/index.js
src/utils.js
test/attributes-option.test.js
test/esModule-option.test.js
test/interpolate-option.test.js
test/loader.test.js
test/minimize-option.test.js
test/root-option.test.js

fix: reduce size of generated modules

---

src/index.js
test/__snapshots__/minimize-option.test.js.snap
test/fixtures/broken-html-syntax.html
test/fixtures/broken-html-syntax.js
test/helpers/normalizeErrors.js
test/minimize-option.test.js

Emit error and return original non minified content
No
No

feat: emit an error on broken HTML syntax when minimization is enabled

---

src/index.js
test/__snapshots__/interpolate-option.test.js.snap
test/__snapshots__/minimize-option.test.js.snap
test/fixtures/broken-interpolation-syntax.html
test/fixtures/broken-interpolation-syntax.js
test/interpolate-option.test.js
test/minimize-option.test.js

fix: emit an error on interpolation compile problems

---

src/plugins/source-plugin.js

`URLObject.hash` can be only `string|null`
No
No

perf: improve source parse

---

README.md

add footnote for `-attributes`

add footnote for `-attributes`

---

src/index.js
src/options.json
src/plugins/source-plugin.js
src/utils.js
test/__snapshots__/attributes-option.test.js.snap
test/attributes-option.test.js

Allow to filter some of sources
No
fixes #198

feat: implement the `filter` option for filtering some of sources

---

src/options.json
test/__snapshots__/validate-options.test.js.snap
test/validate-options.test.js

Better schema validation
In theory yes, but it is more bug than breaking change
No

refactor: improve schema

---

README.md

chore: use latest webpack logo

---

.github/workflows/nodejs.yml
package-lock.json
package.json
src/index.js
src/options.json
src/plugins/source-plugin.js
test/attributes-option.test.js
test/helpers/compile.js
test/helpers/getCompiler.js
test/helpers/getErrors.js
test/helpers/getModuleSource.js
test/helpers/getWarnings.js
test/helpers/normalizeErrors.js

refactor: dropped webpack@4

---

README.md

Responds to #139 and demonstrates an example where an unsupported attribute can be added in the `attributes.list` option.

docs: add example with custom attribute

---

README.md
src/plugins/sources-plugin.js
src/utils.js
test/__snapshots__/sources-option.test.js.snap
test/sources-option.test.js

feat: disable default sources

---

src/runtime/getUrl.js
src/utils.js
test/__snapshots__/esModule-option.test.js.snap
test/__snapshots__/loader.test.js.snap
test/__snapshots__/minimize-option.test.js.snap
test/__snapshots__/preprocessor-option.test.js.snap
test/__snapshots__/sources-option.test.js.snap
test/helpers/execute.js
test/helpers/getCompiler.js
test/runtime/__snapshots__/getUrl.test.js.snap

Sources import with new URL
No
No

feat: sources import with new URL

---

package-lock.json
package.json

update deps before release
No
No

chore(deps): update before release

---

.gitignore
package-lock.json
package.json
src/plugins/sources-plugin.js
src/utils.js
test/__snapshots__/esModule-option.test.js.snap
test/__snapshots__/loader.test.js.snap
test/__snapshots__/minimize-option.test.js.snap
test/__snapshots__/preprocessor-option.test.js.snap
test/__snapshots__/sources-option.test.js.snap
test/fixtures/entry.js
test/fixtures/template-html.html
test/helpers/getModuleSource.js
test/loader.test.js

fix: invalid URL for runtime helpers

---

README.md

fix: lint on master

---

package-lock.json
package.json

fixes https://github.com/webpack-contrib/html-loader/pull/460
No, theoretically, `html-minifier-terser` can have regressions, so it should be considered as bugs
No

feat: update html minifier
